<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FriendsTown.Data\FriendsTown.Data.csproj" />
    <ProjectReference Include="..\FriendsTown.Domain\FriendsTown.Domain.csproj" />
  </ItemGroup>

</Project>
